toArray method fix, constructor checks, new tests
Enterwell/js-enum-helper pull request #1
Opened 2018-02-02 17:37 UTC by mateikki

- toArray method updated to work with non-sequential enum values
- type checks added to enum constructor
- tests updated

2018-02-02 17:58 UTC, AleksandarDev approved these changes

2018-02-02 18:02 UTC, AleksandarDev requested changes
Please update the changelog and bump the version (patch?)

2018-02-02 18:39 UTC, gliba008 submitted a review, later dismissed

2018-02-05 10:07 UTC, AleksandarDev approved these changes

2018-03-22 21:54 UTC, AleksandarDev commented
@mateikki Bump.

2018-03-30 11:51 UTC, merged